<html>
<head>
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    <style>
        div .card {
            display: inline-block;
        }
        .jumbotron {
            background-image: url("https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQi0z1AasOA7TXp_L620-GP7I-EZaGYT71i0YvbkmIsMNtlR4kl");
            background-repeat: repeat;
            
        }

    </style>
</head>
<body style="background-color:#FAEBD7">
    <div class="container">
        <header>
        <!-- jumbotrón -->
        <div class="jumbotron text-center">
            <h1 class="display-4">Despliegue de aplicaciones web</h1>
        </div>

        <!-- navbar -->
        
            <nav class="navbar navbar-expand-lg navbar-light bg-light mb-5 border border-dark rounded-pill">
            <a class="navbar-brand" href="index.php">Home</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="php.php">Php <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="java.php">Java <span class="sr-only">(current)</span></a>
                    </li>
                </ul>
                </div>
            </nav>
        
        </header>